import type { Metadata } from 'next'
import { Inter } from 'next/font/google'


import { ThemeProvider } from "@/components/theme-provider"
import { ClerkProvider } from '@clerk/nextjs'

import './globals.css'
import { cn } from '@/lib/utils';
import { Toaster } from 'sonner';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Twitch-Clone',
  description: 'Generated by create next app and developed by Michael',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body className={cn("text-white/90", inter.className)}>
      <ThemeProvider
            attribute="class"
            forcedTheme="dark"
            storageKey='livegame-keys'
          >
            <Toaster theme="light" position="bottom-center" />
        {children}
        </ThemeProvider>
        </body>
    </html>
    </ClerkProvider>
  )
}
